from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram

# ── Counters ─────────────────────────────────

funding_payments_total = Counter(
    "funding_payments_total",
    "Total funding payments collected",
    ["exchange", "symbol"],
)

trades_executed_total = Counter(
    "trades_executed_total",
    "Total trades executed",
    ["exchange", "symbol", "side", "market"],
)

signals_generated_total = Counter(
    "signals_generated_total",
    "Total signals generated by strategy",
    ["type"],
)

errors_total = Counter(
    "errors_total",
    "Total errors by component",
    ["component", "error_type"],
)

# ── Gauges ───────────────────────────────────

positions_open = Gauge(
    "positions_open",
    "Number of currently open positions",
    ["exchange"],
)

capital_total_usd = Gauge(
    "capital_total_usd",
    "Total capital in USD",
)

pnl_unrealized_usd = Gauge(
    "pnl_unrealized_usd",
    "Unrealized P&L in USD",
)

pnl_realized_usd = Gauge(
    "pnl_realized_usd",
    "Realized P&L in USD",
)

funding_rate_current = Gauge(
    "funding_rate_current",
    "Current funding rate",
    ["exchange", "symbol"],
)

websocket_connected = Gauge(
    "websocket_connected",
    "WebSocket connection status (1=connected, 0=disconnected)",
    ["exchange"],
)

# ── Histograms ───────────────────────────────

execution_latency_seconds = Histogram(
    "execution_latency_seconds",
    "Order execution latency",
    ["exchange"],
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)

order_fill_slippage_bps = Histogram(
    "order_fill_slippage_bps",
    "Order fill slippage in basis points",
    ["exchange", "symbol"],
    buckets=(0.5, 1, 2, 5, 10, 25, 50, 100),
)

evaluation_cycle_duration_seconds = Histogram(
    "evaluation_cycle_duration_seconds",
    "Duration of one strategy evaluation cycle",
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0),
)
